### ISSUE TITLE
Whois NPEs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#214]
```
This occured while whoising a random person via PM. It appears that 

[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:JZTech102!jztech101@crabhost.org PRIVMSG WaveTactDev :level Zarthus
[2014/11/05 12:15:55] [pool-1-thread-3] [INFO] org.pircbotx.output.OutputRaw - 
WHOIS Zarthus
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 311 WaveTactDev Zarthus Zarthus zarth.us * :Zarthus
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 319 WaveTactDev Zarthus :@#zarthus #minecraft #lobby #FTB 
#minecrafthelp #sponge #bukkit #bukkitdev #Werewolf #coders @#help #EliteBNC 
@#acronyms @#dragonweyr #Direwolf20 @#regolf +#mIRC-Bots +#PanicBNC +#mIRC 
#cloudbot #esper #science #drtshock #cobalt #idle #KSPOfficial #linux 
#hearthstone #Ultros +#LayerBNC @#Wolfbot_Debug #espertrivia 
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 312 WaveTactDev Zarthus chaos.esper.net :In memory of Josh 
'Redeemer' Bard (Dallas, TX)
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 301 WaveTactDev Zarthus :I'm not here or not in the mood. 
(If you need EsperNet staff assistance, please /join #dragonweyr) (since Mon 
Nov 03 19:33:19 2014)
[2014/11/05 12:15:55] [botPool0-bot0] [ERROR] org.pircbotx.PircBotX - Exception 
encountered when parsing line
org.pircbotx.exception.DaoException: UnknownUser: Zarthus
    at org.pircbotx.UserChannelDao.getUser(UserChannelDao.java:90)
    at org.pircbotx.InputParser.processServerResponse(InputParser.java:747)
    at org.pircbotx.InputParser.handleLine(InputParser.java:339)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:292)
    at org.pircbotx.PircBotX.connect(PircBotX.java:253)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:154)
    at org.pircbotx.MultiBotManager.executeBot(MultiBotManager.java:225)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:235)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:228)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 313 WaveTactDev Zarthus :is an IRC Operator
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 671 WaveTactDev Zarthus :is using a secure connection
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 330 WaveTactDev Zarthus Zarthus :is logged in as
[2014/11/05 12:15:55] [botPool0-bot0] [INFO] org.pircbotx.InputParser - 
:calamity.esper.net 318 WaveTactDev Zarthus :End of /WHOIS list.
[2014/11/05 12:15:56] [pool-1-thread-3] [INFO] org.pircbotx.output.OutputRaw - 
PRIVMSG JZTech102 :Zarthus is a Regular User! (3)


```

Original issue reported on code.google.com by `jzhou2...@gmail.com` on 5 Nov 2014 at 5:26

**Comment by jztech101** [comment]
This looks to be fixed
