### ISSUE TITLE
Reconnect issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#222]
```
I forgot if I've brought this up before with you. Forgive me if I have. But it 
seems that startBot() is not working properly to reconnect the bot when it gets 
disconnected due to netsplits being annoying.

It does this:
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] org.pircbotx.PircBotX 
- Connected to server.
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.output.OutputRaw - CAP LS
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.output.OutputRaw - NICK WaveTact
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.output.OutputRaw - USER WaveTact 8 * :WaveTact
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - :anarchy.esper.net NOTICE * :*** Looking up your 
hostname...
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - :anarchy.esper.net NOTICE * :*** Checking Ident
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - :anarchy.esper.net NOTICE * :*** No Ident response
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - :anarchy.esper.net NOTICE * :*** Found your hostname
[2014/12/21 01:31:02] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - :anarchy.esper.net CAP * LS :account-notify 
away-notify extended-join multi-prefix sasl tls
, pauses for a bit, then
[2014/12/21 01:31:40] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.InputParser - ERROR :Closing Link: bots.techcavern.com (Connection 
timed out)
[2014/12/21 01:31:40] [ForkJoinPool-1-worker-114] [INFO] org.pircbotx.PircBotX 
- Socket is closed, stopping read loop and shutting down
[2014/12/21 01:32:00] [ForkJoinPool-1-worker-114] [INFO] 
org.pircbotx.output.OutputRaw - PRIVMSG #techcavern :Reconnecting...

```

Original issue reported on code.google.com by `jzhou2...@gmail.com` on 21 Dec 2014 at 1:35

**Comment by Cypherke** [comment]
Not sure if related:
[listenerPool0-thread28980] INFO org.pircbotx.output.OutputRaw - PONG blacklotus.ca.us.quakenet.org
[main] INFO org.pircbotx.output.OutputRaw - PING 1436174499
[main] INFO org.pircbotx.output.OutputRaw - PING 1436174799
[main] INFO org.pircbotx.output.OutputRaw - PING 1436175099
[main] INFO org.pircbotx.output.OutputRaw - PING 1436175399
[main] ERROR org.pircbotx.PircBotX - Exception encountered when reading next line from server
java.net.SocketException: Network is unreachable
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:250)
        at org.pircbotx.PircBotX.connect(PircBotX.java:236)
        at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
        at be.cypherke.jbot.Jbot.<init>(Jbot.java:46)
        at be.cypherke.jbot.Jbot.main(Jbot.java:107)
[main] WARN org.pircbotx.Channel - Channel #9lives.ircraft mode '+stnCN' is stale
[main] WARN org.pircbotx.Channel - Channel #9lives.be mode '+tnCN' is stale
[main] WARN org.pircbotx.Channel - Channel #9lives.ircraft mode '+stnCN' is stale
[main] WARN org.pircbotx.Channel - Channel #9lives.be mode '+tnCN' is stale
[main] INFO org.pircbotx.dcc.DccHandler - Terminating all transfers waiting to be accepted
Jbot::Jbot() - Exception catched while starting the bot!
java.net.UnknownHostException: irc.quakenet.org: unknown error
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1255)
        at java.net.InetAddress.getAllByName(InetAddress.java:1171)
        at java.net.InetAddress.getAllByName(InetAddress.java:1105)
        at org.pircbotx.PircBotX.connect(PircBotX.java:191)
        at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
        at be.cypherke.jbot.Jbot.<init>(Jbot.java:46)
        at be.cypherke.jbot.Jbot.main(Jbot.java:107)

output of CapHandlers:
EnableCapHandler(cap=multi-prefix, ignoreFail=true)
EnableCapHandler(cap=away-notify, ignoreFail=true)

also
builder.setAutoReconnect(true); is used

version 2.0.1

**Comment by jztech101** [comment]
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.PircBotX - ---Starting Connect attempt 1/5---
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.PircBotX - Connected to server.
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.output.OutputRaw - CAP LS
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.output.OutputRaw - NICK Hay1ee
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.output.OutputRaw - USER Hay1ee 8 \* :Hay1ee
[2015/07/17 10:38:48] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - :availo.esper.net NOTICE \* :**\* Looking up your hostname...
[2015/07/17 10:38:49] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - :availo.esper.net NOTICE \* :**\* Checking Ident
[2015/07/17 10:38:49] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - :availo.esper.net NOTICE \* :**\* Found your hostname
[2015/07/17 10:38:53] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - :availo.esper.net NOTICE \* :**\* No Ident response
[2015/07/17 10:38:54] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - :availo.esper.net CAP \* LS :account-notify away-notify extended-join multi-prefix sasl tls
[2015/07/17 10:38:54] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - PING :1E17A118
[2015/07/17 10:38:54] [listenerPool1-thread56] [INFO] org.pircbotx.output.OutputRaw - PONG 1E17A118
[2015/07/17 10:39:01] [botPool0-bot0] [INFO] org.pircbotx.InputParser - PING :tepper.freenode.net
[2015/07/17 10:39:01] [listenerPool0-thread46] [INFO] org.pircbotx.output.OutputRaw - PONG tepper.freenode.net
[2015/07/17 10:39:32] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.InputParser - ERROR :Closing Link: c-24-0-95-126.hsd1.nj.comcast.net (Connection timed out)
[2015/07/17 10:39:32] [ForkJoinPool-1-worker-18] [INFO] org.pircbotx.PircBotX - Socket is closed, stopping read loop and shutting down

Still an issue. I disconnected, then reconnected. (Using .startBot)

**Comment by TheLQ** [comment]
I've found the issue. Basically last year I changed cap handers to add themselves from a list when finished. However some old code didn't get removed and it thought all the CAP code was finished on reconnect. The server then times out because PircBotX didn't respond to its `CAP * LS`

Should be fixed now
