### ISSUE TITLE
DCC drops out after 30Mb

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pircbotx/pircbotx#237]
```
What steps will reproduce the problem?
1. join #horriblesubs on irc.rizon.net
2. request a file with /CR-FRANCE|NEW xdcc send #number

What is the expected output? What do you see instead?
Transfer halts after 28-30Mb

What version of the product are you using? On what operating system?
Snapshot 13/3/2015 running on debian (raspberry pi)

Please provide any additional information below.
Issue does not occur when sending files from my pc via dcc 


```

Original issue reported on code.google.com by `client...@gmail.com` on 13 Mar 2015 at 4:45

**Comment by TheLQ** [comment]
@clienthax Your issue has been moved here

**Comment by clienthax** [comment]
@TheLQ I think this may of been a bug in the os/jre at the time considering the odd way of getting it working by lowering the buffer size

**Comment by Tenshinhan521** [comment]
I've got the same problem here. Randomly the download crashes during the transfer, sometimes after 98 % complete.

The log shows the following exception:

2016-07-13 20:20:33 ERROR DownloadTask:36 - Error
java.net.SocketException: Connection reset by peer: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:141)
    at org.pircbotx.dcc.ReceiveFileTransfer.transferFile(ReceiveFileTransfer.java:74)
    at org.pircbotx.dcc.FileTransfer.transfer(FileTransfer.java:70)
    at myxdccdl.model.DownloadTask.transferAndSaveFile(DownloadTask.java:34)
    at myxdccdl.model.DownloadTask.run(DownloadTask.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Any suggestions? Just increase the buffer size?

**Comment by clienthax** [comment]
@Tenshinhan521 oddly, try decreasing it, as above thats what worked for me
setDccTransferBufferSize(1024*10)

**Comment by Tenshinhan521** [comment]
@clienthax 
Thx for the advice i am going to try it and  i  will inform you about the result

**Comment by Tenshinhan521** [comment]
Ok, if I'm right the default buffersize is according to the Configuration.class 1024 byte.

/**
         \* Size of the DCC file transfer buffer, default 1024 bytes
         */
        protected int dccTransferBufferSize = 1024;

 That is why @clienthax you increased the buffersize in fact by setDccTransferBufferSize(1024_10). I had to increase it to 1024_100 in order to get in working most of the time for my internet connection.

Furthermore I implemented a handling for trying the download again after socket timeout. All together I can download the needed files now realibly.

**Comment by MaggiWuerze** [comment]
why is this issue closed? the problem still persists with jdk 11 and the only way to fix it is increasing the buffersize manually when building the bot.

**Comment by MaggiWuerze** [comment]
and even that does not work consistently

**Comment by hoerup** [comment]
Have you tried to debug it with wireshark and see what happens on the network layer ?

**Comment by MaggiWuerze** [comment]
if you want i could give you a wireshark file that shows the whole traffic from shortly before to shortly after, but there is nothing noteworthy (at least to my eyes). It seems to just stop transmitting.
the filetransfer object is still alive and there is no exception, the _bytesTransfered_ field just stops updating

**Comment by jenga201** [comment]
My pull request today addresses slow / breaking outgoing file transfer.
The same could be applied to receiving files.
I'll look into this soon.

**Comment by MaggiWuerze** [comment]
that's great thanks a lot

**Comment by hoerup** [comment]
@MaggiWuerze  is your problem related to receiving of sending files ?

**Comment by MaggiWuerze** [comment]
edit: sry
its related to receiving

**Comment by hoerup** [comment]
Just for reference / history : the PR that jenga201 is writing about is #378

**Comment by jenga201** [comment]
@MaggiWuerze Please give some feedback on #379 if you get a chance.

**Comment by MaggiWuerze** [comment]
i'll look into it

**Comment by Vodes** [comment]
Any news on this? I have the same problem

**Comment by hoerup** [comment]
I will asume that #378 and #379 fixed this

**Comment by Vodes** [comment]
This is not fixed (partially). Receiving works fine on my windows but cuts out at around 300-350mb on my ubuntu machine. Filesize doesnt seem to matter.
Using 22.04.2020 Snapshot of Pircbotx 2.3 (also happens on 2.2 Release).
Libraries are up-to-date.

Videos of what's happening:
on Windows: https://streamable.com/q419aj
on Linux: https://streamable.com/4n2fno

**Comment by MaggiWuerze** [comment]
@Vodes funny thing, my tests were also with the dcc of HorribleSubs. Nice to see it might not be me after all...

**Comment by Vodes** [comment]
@MaggiWuerze yeah you can see on my profile what I'm trying to to.

I just don't get why it works fine on Windows but doesn't on Linux...

**Comment by MaggiWuerze** [comment]
@Vodes nice, I'm trying to write a web downloader for dcc so I can add downloads directly to my server where my Plex is running. 
See my profile

**Comment by MaggiWuerze** [comment]
So this really seems to be a linux problem. running it natively or in docker on my windows machine does not show this issue, but on ubuntu (or i guess any other linux distro) it cuts off after some time.
I already set the external ip. In my logs the connection gets terminated by the bot sending me the file 180 seconds after my app stops showing any progress and logs:

> xdcc_webloader  | 2023-12-11T18:47:30.054Z ERROR 1 --- [erPool0-thread6] d.m.xdccloader.irc.IrcEventListener      : org.pircbotx.exception.DccException: FILE_TRANSFER_CANCELLED from user Okita1: User closed socket

> xdcc_webloader  | 2023-12-11T18:47:30.061Z  INFO 1 --- [  tnsP34P0_bot1] org.pircbotx.InputParser                 : :Okita1!~Gin@time.for.a.new.lesson NOTICE tnsP34P0 :** Closing Connection: DCC Timeout (180 Sec Timeout)

Any help would be greatly appreciated
