### ISSUE TITLE
[INVALID] ChanServ set mode on user Error

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#244]
[2015/05/21 14:39:39] [botPool0-bot0] [ERROR] org.pircbotx.PircBotX - Exception encountered when parsing line :ChanServ!ChanServ@services. MODE ##neobotwar +o JZTech101
org.pircbotx.exception.DaoException: UnknownUser: ##neobotwar
    at org.pircbotx.UserChannelDao.getUser(UserChannelDao.java:99)
    at org.pircbotx.InputParser.processMode(InputParser.java:929)
    at org.pircbotx.InputParser.processCommand(InputParser.java:608)
    at org.pircbotx.InputParser.handleLine(InputParser.java:354)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:388)
    at org.pircbotx.PircBotX.connect(PircBotX.java:337)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:187)
    at org.pircbotx.MultiBotManager.executeBot(MultiBotManager.java:245)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:256)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:248)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Happens when chanserv sets a mode on a user.

**Comment by jztech101** [comment]
oh I see it is now setUserLevelPrefixes() instead of setChannelPrefixes() (Whoops)
