### ISSUE TITLE
IRCv3 Tags ImmutableMap -> null value in entry

### ISSUE THREAD

**Issue by DQKev** [pircbotx/pircbotx#246]
Google's ImmutableMap does not allow a null value.
You need to find a other way, maybe instead of null store a empty string "" ?

**Comment by TheLQ** [comment]
There shouldn't be null values in the first place. Do you have a stack trace?

**Comment by DQKev** [comment]
Its on
tags.put(parts[0], (parts.length == 2 ? (parts[1]) : null));
For example:
String line = "@color=;display-name=Gamerboy2424;emotes=34:0-8;subscriber=0;turbo=0;user-type= ";

When there is no value for a key, we gonna add null.
Wich is normaly right for the value, but Google doesnt't like null value ;)
Normaly @color should result in value =null

Example Stacktrace
[main] INFO org.pircbotx.InputParser - @color=#FF0000;display-name=Elosatandoxy;emotes=;subscriber=1;turbo=0;user-type=mod :elosatandoxy!elosatandoxy@elosatandoxy.tmi.twitch.tv PRIVMSG #grossie_gore :merci
[main] ERROR org.pircbotx.PircBotX - Exception encountered when parsing line @color=#FF0000;display-name=Elosatandoxy;emotes=;subscriber=1;turbo=0;user-type=mod :elosatandoxy!elosatandoxy@elosatandoxy.tmi.twitch.tv PRIVMSG #grossie_gore :merci
java.lang.NullPointerException: null value in entry: emotes=null
    at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:33)
    at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:135)
    at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:206)
    at org.pircbotx.InputParser.handleLine(InputParser.java:309)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:388)
    at org.pircbotx.PircBotX.connect(PircBotX.java:337)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:187)

**Comment by DQKev** [comment]
Can you close this issue? Forgot to mention it on the commit to close it :)
