### ISSUE TITLE
AWAY Message NPE

### ISSUE THREAD

**Issue by jztech101** [pircbotx/pircbotx#250]
[2015/07/06 16:04:48] [botPool0-bot0] [INFO] org.pircbotx.InputParser - :(Insert hostmask here) AWAY :to the eats!
[2015/07/06 16:04:48] [botPool0-bot0] [ERROR] org.pircbotx.PircBotX - Exception encountered when parsing line :(Insert hostmask here) AWAY :to the eats!
java.lang.NullPointerException
    at org.pircbotx.InputParser.processCommand(InputParser.java:626)
    at org.pircbotx.InputParser.handleLine(InputParser.java:354)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:388)
    at org.pircbotx.PircBotX.connect(PircBotX.java:337)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:187)
    at org.pircbotx.MultiBotManager.executeBot(MultiBotManager.java:245)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:256)
    at org.pircbotx.MultiBotManager$BotRunner.call(MultiBotManager.java:248)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by TheLQ** [comment]
Can you try this with the latest snapshots? They haven't been updated in a while but I've just setup travis to deploy them automatically.

**Comment by jztech101** [comment]
Apologies on the delay, it has been fixed
