### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by C3realGuy** [pircbotx/pircbotx#257]
[Thread-0] ERROR org.pircbotx.PircBotX - Exception encountered when parsing line :irc.esylum.net 005 _NICKNAME_ SAFELIST SILENCE KNOCK FNC WATCH=128 CHANLIMIT=#&:30 MAXLIST=be:60 NICKLEN=30 TOPICLEN=307 KICKLEN=307 CHANNELLEN=32 :are available on this server
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:504)
    at java.lang.Integer.parseInt(Integer.java:527)
    at org.pircbotx.ServerInfo.parse005(ServerInfo.java:180)
    at org.pircbotx.ServerInfo.parse(ServerInfo.java:111)
    at org.pircbotx.InputParser.processServerResponse(InputParser.java:795)
    at org.pircbotx.InputParser.handleLine(InputParser.java:362)
    at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:388)
    at org.pircbotx.PircBotX.connect(PircBotX.java:337)
    at org.pircbotx.PircBotX.startBot(PircBotX.java:187)
    at main.IRCBot.run(IRCBot.java:43)

**Comment by TheLQ** [comment]
Try the latest snapshot, it should be fixed now.

**Comment by C3realGuy** [comment]
[Thread-0] WARN org.pircbotx.ServerInfo - Unparsable server info key 'SILENCE' value '' NumberFormatException: For input string: ""

Looks like it's fixed, can live with a warning :+1: 
Thank you very much!
