### ISSUE TITLE
DCC File transfer not working?

### ISSUE THREAD

**Issue by Yuuki2012** [pircbotx/pircbotx#265]
using .setDccLocalAddress(InetAddress.getLocalHost()) causes >
14:49 DCC SEND from Amatsukaze-chan [192.168.178.12 port 30736]: Test.mkv [400MB]
14:49 DCC connections
14:49  Amatsukaze-chan GET: 0B of 400MB (0%) - 0.00kB/s - ETA (stalled) - Test.mkv

using .setDccLocalAddress(InetAddress.getByName("0.0.0.0")) causes >
14:51 DCC SEND from Amatsukaze-chan [0.0.0.0 port 30757]: File.mkv [400MB]
14:51 DCC can't connect to 0.0.0.0 port 30757

using .setDccLocalAddress(InetAddress.getByName("MY_REMOTE_IP")) causes >
java.net.BindException: Cannot assign requested address: JVM_Bind
    at java.net.DualStackPlainSocketImpl.bind0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
    at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
    at java.net.PlainSocketImpl.bind(Unknown Source)
    at java.net.ServerSocket.bind(Unknown Source)
    at java.net.ServerSocket.<init>(Unknown Source)
    at org.pircbotx.dcc.DccHandler.createServerSocket(DccHandler.java:474)
    at org.pircbotx.dcc.DccHandler.sendFile(DccHandler.java:437)
    at org.pircbotx.dcc.DccHandler.sendFile(DccHandler.java:391)
    at org.pircbotx.output.OutputUser.dccFile(OutputUser.java:120)
    at org.pircbotx.output.OutputUser.dccFileAndTransfer(OutputUser.java:128)
    at Listeners.TriggerListener.onMessage(TriggerListener.java:76)
    at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:71)
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:118)
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:113)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
^ this is obvious, because you can't bind on a public IP ^

using .setDccLocalAddress(InetAddress.getByName("127.0.0.1")) causes >
14:54 DCC SEND from Amatsukaze-chan [127.0.0.1 port 30790]: File.mkv [100MB]
14:54 DCC can't connect to 127.0.0.1 port 30790

Without using > .setDccLocalAddress() < the same thing happens as the 1st one...

Locally, everything works fine, when I'm trying to connect from my server->bot it doesn't work, did I forget anything?

**Comment by TheLQ** [comment]
Most likely this is a public/private address issue. I just pushed out a snapshot ( https://github.com/TheLQ/pircbotx/wiki/DevVersion ) with a new method: ConfigurationBuilder.setDccPublicAddress() . Set the public address to your external address and it should work fine

**Comment by hoerup** [comment]
I assume it's fixed since Yuuki2012 never returned with feedback / updates
