### ISSUE TITLE
CapHandler error

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#270]
I/System.out﹕ 11:42:33,448 |-ERROR in ch.qos.logback.core.joran.event.SaxEventRecorder@d0fbf28 - XML_PARSING - Parsing fatal error on line 20 and column 1 org.xml.sax.SAXParseException: expected start tag notEND_DOCUMENT null@20:1 in java.io.InputStreamReader@d292705
I/System.out﹕ at org.xml.sax.SAXParseException: expected start tag notEND_DOCUMENT null@20:1 in java.io.InputStreamReader@d292705
at org.xmlpull.v1.sax2.Driver.parse(Driver.java:324)
at ch.qos.logback.core.joran.event.SaxEventRecorder.recordEvents(Unknown Source)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(Unknown Source)
at ch.qos.logback.classic.util.ContextInitializer.autoConfig(Unknown Source)
at org.slf4j.impl.StaticLoggerBinder.init(Unknown Source)
at org.slf4j.impl.StaticLoggerBinder.<clinit>(Unknown Source)
at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
at org.pircbotx.cap.EnableCapHandler.<clinit>(EnableCapHandler.java:34)
at org.pircbotx.Configuration$Builder.<init>(Configuration.java:478)

**Comment by TheLQ** [comment]
Looks like your logback.xml file is broken, the CAPHandler was just the first class that tried loading logback.
