### ISSUE TITLE
DCC transfer failure

### ISSUE THREAD

**Issue by gferry** [pircbotx/pircbotx#273]
Hi,

I'm using the latest Dev Version of pircbotx (2.1-20150921), and I can't make a single DCC transfer between my bot and another user, both logged on an UnrealIRCd server (LAN).

When I'm receiving the transfer event, and initiating the actual transfer, I get the following exception (a SocketException) :

java.net.SocketException: Invalid argument or cannot assign requested address
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_66-internal]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_66-internal]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_66-internal]
    at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_66-internal]
    at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_66-internal]
    at java.net.Socket.<init>(Socket.java:434) ~[na:1.8.0_66-internal]
    at java.net.Socket.<init>(Socket.java:328) ~[na:1.8.0_66-internal]
    at org.pircbotx.dcc.DccHandler.acceptFileTransfer(DccHandler.java:319) ~[pircbotx-2.1-20150921.164219-143.jar:na]
    at org.pircbotx.dcc.DccHandler.acceptFileTransfer(DccHandler.java:258) ~[pircbotx-2.1-20150921.164219-143.jar:na]
    at org.pircbotx.hooks.events.IncomingFileTransferEvent.accept(IncomingFileTransferEvent.java:115) ~[pircbotx-2.1-20150921.164219-143.jar:na]

Regular DCC between two users on this server (using IRC clients like weechat or konversation) works fine.
Am I missing something here ?

Thanks a lot for this great library !
Guillaume

**Comment by TheLQ** [comment]
Most likely this is a public/private address issue. I just pushed out a snapshot ( https://github.com/TheLQ/pircbotx/wiki/DevVersion ) with a new method: ConfigurationBuilder.setDccPublicAddress() . Set the public address to your external address and it should work fine

**Comment by gferry** [comment]
Hi Leon,

Thanks for this snapshot. I'll run some more tests based on it, and give you some feedback afterwards.
Guillaume.

**Comment by hoerup** [comment]
I assume that it was fixes, since gferry never returned
