### ISSUE TITLE
null key in entry

### ISSUE THREAD

**Issue by mjmjelde** [pircbotx/pircbotx#274]
I am currently trying to create a irc client/bot for twitch, however every so often the error below is thrown from pircbotx.  The line of code that this occurs on is the startBot() function from the PircBotX class.

```
java.lang.NullPointerException: null key in entry: null=Channel(name=#joindotared, channelId=48999bc0-7e41-4b7f-8bbb-d1c1221a265a, bot=Version{PircBotX 2.1-SNAPSHOT-ed4485d Java IRC bot - github.com/thelq/pircbotx} Connected{true} Server{irc.twitch.tv} Port{6667}, output=org.pircbotx.Channel$1@2079a31a, mode=, topic=, topicTimestamp=0, createTimestamp=0, topicSetter=null, moderated=false, noExternalMessages=false, inviteOnly=false, secret=false, channelPrivate=false, topicProtection=false, channelLimit=-1, channelKey=null, modeChangeLatch=null, modeChangeLock=java.lang.Object@e86805)
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31)
at com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:169)
at org.pircbotx.UserChannelMap.createSnapshot(UserChannelMap.java:105)
at org.pircbotx.UserChannelDao.createSnapshot(UserChannelDao.java:485)
at org.pircbotx.InputParser.processCommand(InputParser.java:553)
at org.pircbotx.InputParser.handleLine(InputParser.java:365)
at org.pircbotx.PircBotX.processNextLine(PircBotX.java:403)
at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:350)
at org.pircbotx.PircBotX.connect(PircBotX.java:338)
at org.pircbotx.PircBotX.startBot(PircBotX.java:188)
at com.mjmfighter.twitchstatistics.irc.TwitchIRC.run(TwitchIRC.java:47)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by TheLQ** [comment]
Have you tried 2.1-SNAPSHOT? https://github.com/TheLQ/pircbotx/wiki/DevVersion

**Comment by mjmjelde** [comment]
Yes I have tried 2.1-SNAPSHOT.  It is currently what I am using.

I dug into the error a bit more and it does not seem to be a fatal error as my program keeps working.  This error only shows when I print out all exceptions that are passed to the onException in my ListenerAdapter class.  

In other words, this error seems to get spammed a lot.  However it will only start appearing if you add an onException listener and start printing out any errors that are passed to it.  Might be something to look into and see why its throwing all the exceptions, but it is not hurting the program from running as of right now

**Comment by hoerup** [comment]
It doesn't solve the issue - but would it be a viable workaround to Use TreeMultimap instead of hasnmultimap since it is not that sensible to null values ?

**Comment by hoerup** [comment]
Is this till a issue with 2.2 or 2.3 snapshot ?

**Comment by roop90** [comment]
Hi,

I just encountered this exception.

`java.lang.NullPointerException: Issue #274: No user snapshot for User ...`

I'm using the latest 2.3-SNAPSHOT version
