### ISSUE TITLE
MultiBotManager fails to stop

### ISSUE THREAD

**Issue by Pupskuchen** [pircbotx/pircbotx#280]
I'm using MultiBotManager to manage my bots but it throws an Exception when stopping the manager because it tries to stop bots that aren't connected (I've let them quit before (because I want to make use of the quitmessage)):
https://github.com/TheLQ/pircbotx/blob/latest/src/main/java/org/pircbotx/MultiBotManager.java#L173

no idea what's happening here because the bot is obviously not connected anymore (at least it shouldn't be), but yeah...

console/log output:

```
[listenerPool0-thread1] INFO org.pircbotx.output.OutputRaw - QUIT :ciao
[botPool0-bot0] INFO org.pircbotx.InputParser - ERROR :Closing link: (bot@host) [Quit: ciao]
[botPool0-bot0] INFO org.pircbotx.dcc.DccHandler - Terminating all transfers waiting to be accepted
[listenerPool0-thread1] INFO org.pircbotx.output.OutputRaw - QUIT :
[listenerPool0-thread1] ERROR org.pircbotx.hooks.managers.ThreadedListenerManager - Exception encountered when executing event MessageEvent([...]) on listener CommandListener
java.lang.RuntimeException: Couldn't pause thread for message delay
    at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:76)
    at org.pircbotx.output.OutputIRC.quitServer(OutputIRC.java:80)
    at org.pircbotx.output.OutputIRC.quitServer(OutputIRC.java:68)
    at org.pircbotx.MultiBotManager.stop(MultiBotManager.java:173)
    [...]
    CommandListener
    [...]
    at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:63)
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:119)
    at org.pircbotx.hooks.managers.ThreadedListenerManager$1.call(ThreadedListenerManager.java:115)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Exception encountered when writing to socket
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:303)
    at org.pircbotx.Utils.sendRawLineToServer(Utils.java:88)
    at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:73)
    ... 12 more
Caused by: java.net.SocketException: Socket is closed
    at sun.security.ssl.SSLSocketImpl.checkEOF(Unknown Source)
    at sun.security.ssl.SSLSocketImpl.checkWrite(Unknown Source)
    at sun.security.ssl.AppOutputStream.write(Unknown Source)
    at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
    at sun.nio.cs.StreamEncoder.implFlush(Unknown Source)
    at sun.nio.cs.StreamEncoder.flush(Unknown Source)
    at java.io.OutputStreamWriter.flush(Unknown Source)
    at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:300)
    ... 14 more
[botPool0-bot0] INFO org.pircbotx.PircBotX - Shutdown has been called, closing InputParser
```

The worst thing is that this doesn't even stop the bot (as in quit the program).
Maybe it's worth mentioning that I want to quit the program by a command issued by a user (thus from within an onMessage Listener).

So, am I doing it wrong or is this a bug?

**Comment by TheLQ** [comment]
It looks like you have a listener with 

bot.send().quitServer("ciao")
multiBotManager.stop()

And then the listener's thread and the main thread are racing. Does it work if you take out the quitServer call and just use stop?

**Comment by Pupskuchen** [comment]
Yeah, that does work - but this way I can't set my custom quit message and it just quits without any message.

**Comment by TheLQ** [comment]
Well for now there's a new method MultiBotManager.stop("ciao") that you can use. I'm still unsure why the exception happens though

**Comment by hoerup** [comment]
Fixed with MultiBotManager.stop("ciao")
