### ISSUE TITLE
RuntimeException: sendRawLineToServer

### ISSUE THREAD

**Issue by MyWay** [pircbotx/pircbotx#300]
```
Caused by java.net.SocketException: Socket is closed
       at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:238)
       at com.android.org.conscrypt.OpenSSLSocketImpl.access$100(OpenSSLSocketImpl.java:63)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:727)
       at java.io.OutputStreamWriter.flushBytes(OutputStreamWriter.java:167)
       at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:158)
       at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:367)
       at org.pircbotx.Utils.sendRawLineToServer(Utils.java:133)
       at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:73)
       at org.pircbotx.output.OutputIRC.changeNick(OutputIRC.java:173)
```

It can happen that the user is connected, send the message/change the nick or whatever and then disconnects. Is this the case?

**Comment by hoerup** [comment]
I don't quite understand your question. Please elaborate
