### ISSUE TITLE
Calling event.getUser().getNick() from a Notice Event throws NullPointerException

### ISSUE THREAD

**Issue by GraysonBriggs** [pircbotx/pircbotx#309]
When receiving a NoticeEvent from Twitch.tv if I call .getUser().getNick() on the event I get this exception, which is silently thrown if you don't surround it with a catch, which has caused quite the headache for a few days now. Using 

`java.lang.NullPointerException
    at base.Bot.onNotice(Bot.java:250)
    at org.pircbotx.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:81)
    at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:52)
    at org.pircbotx.hooks.managers.AbstractListenerManager.executeListener(AbstractListenerManager.java:47)
    at org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable.run(AbstractListenerManager.java:74)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by GraysonBriggs** [comment]
Sorry, I'm not sure how to get the StackTrace to look better

**Comment by ghost** [comment]
Does .getUser() return null or not?

**Comment by GraysonBriggs** [comment]
Yes, sorry I guess it makes sense that .getUser() returns null from a notice. This is also an older version of the issue I wrote before I could look into it. I'm not sure why this version got posted.
