### ISSUE TITLE
Exception encountered when reading next line from server

### ISSUE THREAD

**Issue by jenga201** [pircbotx/pircbotx#322]
This error crops up sometimes.

I'm connected using SSL to irc.rizon.net

05:27:42.837 [main] INFO  org.pircbotx.output.OutputRaw - PING 1468834062
05:28:34.313 [main] ERROR org.pircbotx.PircBotX - Exception encountered when reading next line from server
java.net.SocketException: Connection timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_101]
        at java.net.SocketInputStream.read(SocketInputStream.java:152) ~[na:1.7.0_101]
        at java.net.SocketInputStream.read(SocketInputStream.java:122) ~[na:1.7.0_101]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442) ~[na:1.7.0_101]
        at sun.security.ssl.InputRecord.read(InputRecord.java:480) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:946) ~[na:1.7.0_101]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:903) ~[na:1.7.0_101]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102) ~[na:1.7.0_101]
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283) ~[na:1.7.0_101]
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325) ~[na:1.7.0_101]
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177) ~[na:1.7.0_101]
        at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.7.0_101]
        at java.io.BufferedReader.fill(BufferedReader.java:154) ~[na:1.7.0_101]
        at java.io.BufferedReader.readLine(BufferedReader.java:317) ~[na:1.7.0_101]
        at java.io.BufferedReader.readLine(BufferedReader.java:382) ~[na:1.7.0_101]
        at org.pircbotx.PircBotX.processNextLine(PircBotX.java:366) [pircbotx-2.1-20150921.164219-143.jar:na]
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:350) [pircbotx-2.1-20150921.164219-143.jar:na]
        at org.pircbotx.PircBotX.connect(PircBotX.java:338) [pircbotx-2.1-20150921.164219-143.jar:na]
        at org.pircbotx.PircBotX.startBot(PircBotX.java:188) [pircbotx-2.1-20150921.164219-143.jar:na]
        at ircbot.Bot.<init>(Unknown Source) [bin/:na]
        at ircbot.Bot.main(Unknown Source) [bin/:na]
05:28:34.314 [main] DEBUG org.pircbotx.PircBotX - ---PircBotX shutdown started---
05:28:34.317 [main] DEBUG org.pircbotx.PircBotX - Disconnected.
05:28:34.317 [main] DEBUG o.p.h.m.ThreadedListenerManager - Waiting for listener ircbot.Listener@5fa16fc7 to execute event IncomingFileTransferEvent(user=User(super=UserHostmask$
05:29:00.017 [pool-2-thread-7] INFO  i.p.checkconnection.CheckConnection - Bot is offline, attempting to reconnect.
05:29:00.017 [pool-2-thread-7] ERROR i.p.checkconnection.CheckConnection - Reconnect was called!

**Comment by tobciu** [comment]
there is no problem with pircbotx, you cannot establish a connection to rizon.net: 
**java.net.SocketException: Connection timed out**

**Comment by hoerup** [comment]
as tobciu stated, looks like a configuration problem. I assume that you have found a fix by now - if not please re-open this issue.
