### ISSUE TITLE
Couldn't pause thread for message delay

### ISSUE THREAD

**Issue by hasan5151** [pircbotx/pircbotx#358]
compile group: 'org.pircbotx', name: 'pircbotx', version: '2.0.1'

        bot.stopBotReconnect();
        bot.sendIRC().quitServer();

   Caused by: java.lang.RuntimeException: Couldn't pause thread for message delay
        at org.pircbotx.output.OutputRaw.rawLine(OutputRaw.java:76)
        at org.pircbotx.output.OutputIRC.quitServer(OutputIRC.java:80)
        at org.pircbotx.output.OutputIRC.quitServer(OutputIRC.java:68)

How can i quit from bot? 
Is it possible send message without GenericMessage?

**Comment by hasan5151** [comment]
fixed with implementation 'com.github.pircbotx:pircbotx:2.1'
