### ISSUE TITLE
NoSuchFieldError: WHITESPACE after reopening the project

### ISSUE THREAD

**Issue by OrlowskiAdam** [pircbotx/pircbotx#371]
Hi! Here we go with another one...
I'm struggling with some unexpected error this time. I was enjoying pircbotx using IRC etc. making stuff I described in [#370](https://github.com/pircbotx/pircbotx/issues/370#issue-449685144) and I decided to take a break. I closed my PC and stuff. After a few hours I decided to come back to coding. After I opened the project and start running it, the error appears:

```
[ReadingThread] ERROR net.dv8tion.jda.core.JDA - One of the EventListeners had an uncaught exception
java.lang.NoSuchFieldError: WHITESPACE
	at org.pircbotx.Utils.tokenizeLine(Utils.java:105)
	at org.pircbotx.InputParser.handleLine(InputParser.java:284)
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:275)
	at org.pircbotx.PircBotX.connect(PircBotX.java:236)
	at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
	at Commands.IRC.IRC(IRC.java:39)
	at Commands.Verify.onGuildMessageReceived(Verify.java:163)
	at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:381)
	at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
	at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:96)
	at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
	at net.dv8tion.jda.core.requests.WebSocketClient.onDispatch(WebSocketClient.java:868)
	at net.dv8tion.jda.core.requests.WebSocketClient.onEvent(WebSocketClient.java:766)
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:745)
	at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:903)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:265)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:241)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:767)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:607)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:100)
	at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:59)
```
The funniest thing is I had the same error before, so I copied everything to the fresh maven project and after that everything worked just fine - until I closed my PC again...
As you can see I'm using JDA lib for discord bot support. I've commented out the IRC stuff in my code, it doesn't look like it's a JDA lib issue, because all jda events worked perfectly.

The libs I have in my project:
```
PircBotX
guava
slf4j
slf4j-simple
commons-codec
commons-collections
mysql-connector-java
protobuf-java
okhttp3
okio
nv-websocket-client
trove4j
json
JDA
```

Also my IRC.java
```
import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.exception.IrcException;
import org.pircbotx.hooks.events.ConnectEvent;
import java.io.IOException;
class IRC extends org.pircbotx.hooks.ListenerAdapter {
    private static PircBotX bot;
    private static String name;
    private static int code;

    public void setName(String name) {
        this.name = name;
    }

    public void setCode(int code) {
        this.code = code;
    }

    @Override
    public void onConnect(ConnectEvent event) {
        bot.sendIRC().message("" + name, "Your verification code is: " + code);
        bot.sendIRC().quitServer();
    }

    public void IRC() {
        Configuration configuration = new Configuration.Builder()
                .setName("botName")
                .setServerHostname("hostname")
                .setServerPort(6667)
                .setServerPassword("pass")
                .addAutoJoinChannel("#general")
                .addListener(new IRC())
                .buildConfiguration();

        bot = new PircBotX(configuration);
        try {
            bot.startBot(); //This is line 39
        } catch (IOException | IrcException e) {
            e.printStackTrace();
        }

    }
}
```

and Verify.java (only the fragment where 163rd line is):
```

if (verificationDiscordName.equals(discordName) && verificationPlayerNick.equals(name) && verificationIsVerified.equals("no")) { //These are values taken from database
                            name = name.replaceAll("~", " ");
                            IRC irc = new IRC();
                            irc.setName(name);
                            irc.setCode(verificationCode);
                            try {
                                irc.IRC(); //This is line 163
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
```

Is there some way to overcome this problem? Cuz making fresh project and copying every libraries/classes is hell..

**Comment by OrlowskiAdam** [comment]
Okay, I somehow figured out why this error appears - my PC wasn't shutted down properly (instead of turning off, it went sleep/hibernate). I put all java files in brand-new project, saved it, and this time closed PC by myself. after Turning on, the IRC worked fine as previously.
But why it happens when PC is not turned off manually?

**Comment by jenga201** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/NoSuchFieldError.html
Thrown if an application tries to access or modify a specified field of an object, and that object no longer has that field.
Normally, this error is caught by the compiler; this error can only occur at run time if the definition of a class has incompatibly changed.

That means your project or files didn't fully compile.  You had one version of an Object that didn't have some method you were referencing in another Object.

If you're using an IDE just make sure to clean/build the project before running it after changes.

**Comment by daniel071** [comment]
If anyone is having this error, downgrade the version of guava to 25.0-jre in your maven pom.xml file

```java
# Before
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>31.0.1-jre</version>
</dependency>
```
Fixed version:
```java
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>25.0-jre</version>
</dependency>
```
Then make sure to clean and rebuild for the binaries to work.

**Comment by AiyionPrime** [comment]
Just wanted to leave this here: https://github.com/advisories/GHSA-5mg8-w23w-74h3
All versions prior and equal to guava 29.0 are affected.
You might wanna check if that applies to this project.
