### ISSUE TITLE
ExceptionHandling not working

### ISSUE THREAD

**Issue by MaggiWuerze** [pircbotx/pircbotx#374]
I am starting an irc bot in the background to fullfill a task a user initiated. When the bot encounters an exception like timeout, connection reset or file not found in case of filetransfer i currently have no reliable way to catch and deal with the exceptions (e.g. display them in he frontend). 
The 
`    @Override
    public void onException(ExceptionEvent event) {}
`
method does not catch all exceptions thrown from within the bot thread.

**Comment by hoerup** [comment]
can you assist us and point to concrete thrown exceptions including stacktrace eg. from logging

**Comment by jenga201** [comment]
Events aren't global exception handling.  The actual SendFileTransfer and ReceiveFileTransfer objects would need to register events.

I was actually looking for something similar to catch failures, so will probably address this.

**Comment by jenga201** [comment]
#379 has an onFileTransferComplete event which can be queried for error or success.
If error, the IOException is part of the event.

**Comment by MaggiWuerze** [comment]
Sorry for the late answer

````
2019-08-16 16:52:47.910  WARN 4246 --- [  vwZUx5Dh bot1] org.pircbotx.PircBotX                    : [3/4 address left from irc.rizon.net, 0/1 hostnames left] Failed to connect to irc.rizon.net/80.65.57.18 on port 6667

java.net.ConnectException: Connection timed out (Connection timed out)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:591) ~[na:na]
	at org.pircbotx.PircBotX.connect(PircBotX.java:290) ~[pircbotx-2.3-SNAPSHOT.jar:na]
	at org.pircbotx.PircBotX.startBot(PircBotX.java:187) ~[pircbotx-2.3-SNAPSHOT.jar:na]
	at de.maggiwuerze.xdccloader.events.CustomSpringEventListener.lambda$onDownloadCreationEvent$0(CustomSpringEventListener.java:78) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```` 

Neither of those methods caught it:

````
    @Override
    public void onException(ExceptionEvent event)
    @Override
    public void onConnectAttemptFailed(ConnectAttemptFailedEvent event) 
    @Override
    public void onListenerException(ListenerExceptionEvent event)
````
