### ISSUE TITLE
How not to receive any input?

### ISSUE THREAD

**Issue by OrlowskiAdam** [pircbotx/pircbotx#380]
Hello, I'm struggling with a problem that I cannot overcome. I have my bot connected to the IRC where there're like 12k users at the same time. This causes a pretty big spam in my console, when someone is quitting the irc (like 5 per second).

The problem is that I'm getting weird NPEs when receiving these messages:

```
2019-08-13 12:57:25.706  INFO 9568 --- [       Thread-9] org.pircbotx.InputParser                 : :danny0431!cho@ppy.sh QUIT :ping timeout 180s
2019-08-13 12:57:25.706 ERROR 9568 --- [       Thread-9] org.pircbotx.PircBotX                    : Exception encountered when parsing line :danny0431!cho@ppy.sh QUIT :ping timeout 180s

java.lang.NullPointerException: null
	at org.pircbotx.InputParser.processCommand(InputParser.java:510) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.InputParser.handleLine(InputParser.java:330) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.connect(PircBotX.java:284) ~[pircbotx-2.1.jar:na]
	at org.pircbotx.PircBotX.startBot(PircBotX.java:177) ~[pircbotx-2.1.jar:na]
	at com.example.gottaaimfastwebsite.irc.IRC.startIrc(IRC.java:48) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

Also my bot configuration:
```
private void startIrc() {
        try {
            Configuration configuration = new Configuration.Builder()
                    .setName("name")
                    .setServerHostname("irc.ppy.sh")
                    .setServerPort(6667)
                    .addAutoJoinChannel("#general")
                    .setAutoReconnect(true)
                    .addListener(new Event())
                    .addListener(new IRC())
                    .buildConfiguration();

            bot = new PircBotX(configuration);
            bot.startBot();
        } catch (IOException | IrcException e) {
            e.printStackTrace();
        }
    }
```

Is there any way to disable input? I don't want to receive any logs from IRC actually. I also don't need to struggle with NPE, it doesn't really affect my app.

**Comment by Cypherke** [comment]
First of all, please use the 2.3-snapshot ;)

It all depends of your logging implementation you use. e.g. if you use slf4j-simple you can create a 

> resources/simplelogger.properties

 file with this in:

`org.slf4j.simpleLogger.log.org.pircbotx=error`

so it only logs the errors and not the informational debug messages for all the org.pircbotx classes. Hopefully this points you in the right direction for the setup you use.

**Comment by OrlowskiAdam** [comment]
Using 2.3-snapshot does not solve the problem.
Also I don't have any logger in [pom.xml](https://pastebin.com/rVVzHBXh) file, so this trick with proporties also does not work. Adding simple logger and creating that file did not work as well, it could not resolve configuration property.

**Comment by Cypherke** [comment]
seems like you're using spring-boot: check this out https://howtodoinjava.com/spring-boot/logging-application-properties/

**Comment by OrlowskiAdam** [comment]
Adding this line `logging.level.org.pircbotx=OFF` to `application.proporties` fixed this problem. Thanks for the assist!
