### ISSUE TITLE
Issue with string parsing in various places

### ISSUE THREAD

**Issue by mattford** [pircbotx/pircbotx#390]
Getting the following during server connection startup: 
```
03-28 13:35:31.897 4456-4771/uk.org.mattford.scoutlink E/org.pircbotx.PircBotX: Exception encountered when parsing line :cypress.scoutlink.net 372 FordyKindle : 
    java.lang.StringIndexOutOfBoundsException: length=0; index=1
        at java.lang.String.indexAndLength(String.java:500)
        at java.lang.String.substring(String.java:1313)
        at org.pircbotx.InputParser.processServerResponse(InputParser.java:689)
        at org.pircbotx.InputParser.handleLine(InputParser.java:324)
        at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342)
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295)
        at org.pircbotx.PircBotX.connect(PircBotX.java:284)
        at org.pircbotx.PircBotX.startBot(PircBotX.java:177)
        at uk.org.mattford.scoutlink.irc.IRCService.lambda$connect$3$IRCService(IRCService.java:156)
        at uk.org.mattford.scoutlink.irc.-$$Lambda$IRCService$poH075nSF-QzFe-Kp1-oU-edLxo.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
```

and this when mode changes:
```
03-28 13:35:41.834 4456-4771/uk.org.mattford.scoutlink E/org.pircbotx.PircBotX: Exception encountered when parsing line :ChanServ!ChanServ@services.scoutlink.net MODE #test -o :Fordy
    java.lang.RuntimeException: Unable to parse hostmask :Fordy
        at org.pircbotx.UserHostmask.<init>(UserHostmask.java:94)
        at org.pircbotx.Configuration$BotFactory.createUserHostmask(Configuration.java:2206)
        at org.pircbotx.InputParser$OpChannelModeHandler.handleMode(InputParser.java:903)
        at org.pircbotx.InputParser.processMode(InputParser.java:846)
        at org.pircbotx.InputParser.processCommand(InputParser.java:541)
        at org.pircbotx.InputParser.handleLine(InputParser.java:330)
        at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342)
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295)
        at org.pircbotx.PircBotX.connect(PircBotX.java:284)
        at org.pircbotx.PircBotX.startBot(PircBotX.java:177)
        at uk.org.mattford.scoutlink.irc.IRCService.lambda$connect$3$IRCService(IRCService.java:156)
        at uk.org.mattford.scoutlink.irc.-$$Lambda$IRCService$poH075nSF-QzFe-Kp1-oU-edLxo.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at org.pircbotx.UserHostmask.<init>(UserHostmask.java:89)
        at org.pircbotx.Configuration$BotFactory.createUserHostmask(Configuration.java:2206) 
        at org.pircbotx.InputParser$OpChannelModeHandler.handleMode(InputParser.java:903) 
        at org.pircbotx.InputParser.processMode(InputParser.java:846) 
        at org.pircbotx.InputParser.processCommand(InputParser.java:541) 
        at org.pircbotx.InputParser.handleLine(InputParser.java:330) 
        at org.pircbotx.PircBotX.processNextLine(PircBotX.java:342) 
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:295) 
        at org.pircbotx.PircBotX.connect(PircBotX.java:284) 
        at org.pircbotx.PircBotX.startBot(PircBotX.java:177) 
        at uk.org.mattford.scoutlink.irc.IRCService.lambda$connect$3$IRCService(IRCService.java:156) 
        at uk.org.mattford.scoutlink.irc.-$$Lambda$IRCService$poH075nSF-QzFe-Kp1-oU-edLxo.run(lambda) 
        at java.lang.Thread.run(Thread.java:818) 
```

I'm using Java 1.8 and version 2.1 of Pircbotx (2.2 not available via maven, but have checked the diff and I don't think 2.2 fixes this)

I think it's related to StringUtils.split not returning empty segments of the string in the array. E.g.,
`StringUtils.split(":FordyApp", ":").length == 1`
whereas
`StringUtils.split("xxx:FordyApp", ":").length == 2`

**Comment by mattford** [comment]
Actually I cloned the repo to try to get a PR for this in, and I see @hoerup has fixed both these issues in a commit yesterday, so will close this issue and wait patiently for those fixes to be release :)
