### ISSUE TITLE
Out of bounds exception on every empty MOTD line

### ISSUE THREAD

**Issue by DrHaribo** [pircbotx/pircbotx#402]
pircbotx 2.2: When the server sends a 372 with an empty message, an exception gets logged:

2021-07-28T22:43:23.070+0000 ERROR [ForkJoinPool-1-worker-29] org.pircbotx.PircBotX - Exception encountered when parsing line :darwin.freenode.net 372 Mybot :
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.base/java.lang.String.substring(String.java:1841)
        at org.pircbotx.InputParser.processServerResponse(InputParser.java:815)
        at org.pircbotx.InputParser.handleLine(InputParser.java:378)
        at org.pircbotx.PircBotX.processNextLine(PircBotX.java:404)
        at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:351)
        at org.pircbotx.PircBotX.connect(PircBotX.java:339)
        at org.pircbotx.PircBotX.startBot(PircBotX.java:187)

**Comment by hoerup** [comment]
Was fixed in 7f1e6a1b91d633dd62a7e5e70f624e476d59af89 

If you build agains latest snapshot from jitpack https://jitpack.io/#pircbotx/pircbotx/master-SNAPSHOT  you shouldn't see it anymore
