### ISSUE TITLE
java.lang.NoSuchFieldError: WHITESPACE

### ISSUE THREAD

**Issue by hasandiwan** [pircbotx/pircbotx#417]
Latest version is giving me this message, code follows:

>private PircBotX bot = new PircBotX(new org.pircbotx.Configuration.Builder().setName("cruyffBot").addServer("irc.chatautism.com").buildConfiguration());

> bot.startBot();

> if (bot.isConnected()) {
> bot.sendIRC().message(config.getOrDefault("irc.nick", "JohannCruyff8"), "Your bot is connected!");
> }

... finally, this awards me the following stacktrace:

Caused by: java.lang.NoSuchFieldError: WHITESPACE
	at org.pircbotx.Utils.tokenizeLine(Utils.java:166)
	at org.pircbotx.PircBotX.sendRawLineToServer(PircBotX.java:368)
	at org.pircbotx.Utils.sendRawLineToServer(Utils.java:133)
	at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:109)
	at org.pircbotx.output.OutputRaw.rawLineNow(OutputRaw.java:94)
	at org.pircbotx.output.OutputCAP.getSupported(OutputCAP.java:37)
	at org.pircbotx.PircBotX.connect(PircBotX.java:277)
	at org.pircbotx.PircBotX.startBot(PircBotX.java:177)
	at us.d8u.balance.Controller.initialize(Controller.java:3155)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)

**Comment by TheLQ** [comment]
I don't know where this came from. There's no WHITESPACE field in tokenizeLine we use this https://github.com/google/guava/blob/master/guava/src/com/google/common/base/CharMatcher.java#L147-L149

Closing old issues, re-open if this still happens
